"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](env_bg)\
$os\
$shell\
$time\
(\
[](fg:prev_bg bg:id_bg)\
$username\
$hostname\
)\
[](fg:prev_bg bg:dir_bg)\
$directory\
(\
[](fg:prev_bg bg:git_bg)\
$git_branch\
$git_status\
$git_state\
)\
[](fg:prev_bg bg:env_bg)\
[ \
${custom.vi_mode_bash}\
${env_var.VI_MODE_PROMPT}\
](bg:env_bg fg:light_fg)\
[ ](prev_bg)"""

add_newline = false

palette = 'default'

[env_var.VI_MODE_PROMPT]
default = ''
format = '$env_value'

[custom.vi_mode_bash]
command = 'echo "\q{blerc/vim-mode}"'
format = '$output'
ignore_timeout = true # PowerShell is slow to test
os = 'unix'
unsafe_no_escape = true # Required for the escape sequence
when = 'test "$STARSHIP_SHELL" = "bash"' # This needs to work in PowerShell

[os]
disabled = false
style = "bg:env_bg fg:light_fg"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[shell]
disabled = false
bash_indicator = "bash"
cmd_indicator = "cmd"
format = "[ $indicator ]($style)"
powershell_indicator = "posh"
pwsh_indicator = "pwsh"
style = "bg:env_bg fg:light_fg"

[username]
format = '[ $user]($style)'
show_always = false
style_user = "bg:id_bg fg:light_fg"
style_root = "bg:id_bg fg:light_fg"

[hostname]
format = "[ $hostname ]($style)"
style = "bg:id_bg fg:light_fg"

[directory]
before_repo_root_style = "bold"
format = "[ $path ]($style)"
repo_root_format = "[ \uF408 $repo_root$path [$read_only]($read_only_style)]($style)"
repo_root_style = "bold"
style = "bg:dir_bg fg:dark_fg"
truncation_length = 5
truncation_symbol = '.../'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
format = '[ $symbol $branch ]($style)'
style = "bg:git_bg fg:light_fg"
symbol = ""

[git_status]
format = '([($stashed )( ($untracked )($modified )($renamed )($deleted )($conflicted ))($staged )($ahead_behind )]($style))'
style = "bg:git_bg fg:light_fg"
stashed = ' ${count}'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${count}"
conflicted = "!${count}"
deleted = "-${count}"
renamed = "»${count}"
modified = "~${count}"
staged = " ${count}"
untracked = "?${count}"

[git_state]
format = '[$state ($progress_current/$progress_total )]($style)'
style = "bg:git_bg fg:light_fg"
rebase = "\uE728"
merge = "\uE727"
revert = "\uF0E2"
cherry_pick = "\uE29B"

[time]
disabled = false
time_format = "%R"
style = "bg:time_bg"
format = '[[ $time ](fg:light_fg bg:env_bg)]($style)'

[line_break]
disabled = true

[palettes.default]
env_bg = "#3A3A3A"
dark_fg = "#282828"
dir_bg = "cyan"
git_bg = "#6F42C1"
id_bg = "#F96C2A"
light_fg = "#FFFFFF"

