---
jobs:
  pre-commit:
    name: Pre-Commit
    uses: gtbuchanan/tooling/.github/workflows/pre-commit.yml@main
    with:
      use-pnpm: true
name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
